const quotes = [
  "“Jangan menunggu waktu yang tepat, karena waktu tidak akan pernah tepat.”",
  "“Hidup itu seperti naik sepeda, lo harus terus bergerak biar gak jatuh.” - Einstein",
  "“Bermimpilah setinggi langit, kalau jatuh ya nyangkut di awan dulu lah.” 😎",
  "“Yang penting bukan seberapa cepat kamu sampai, tapi seberapa tekun kamu melangkah.”",
  "“Gagal itu biasa, nyerah itu baru bahaya.”",
  "“Belajar koding itu kayak ngedeketin cewek—harus sabar, kadang error.” 😂",
  "“Sukses itu kombinasi antara kerja keras + doa + ngopi + debugging.”",
  "“Do your best, and let Allah do the rest.” ☕",
  "“Semangat itu kayak mandi, harus tiap hari biar gak bau.” 😂",
  "“Lo kuat bukan karena gak pernah jatuh, tapi karena selalu bangkit.”",
  "“Satu-satunya hal yang menghalangi mimpi lo itu... rasa malas.”",
  "“Jangan takut gagal, takutlah kalo gak nyoba sama sekali.”",
  "“Belajar HTML tuh kayak belajar abjad... awal dari segalanya.”",
  "“Kalau jalan lo gelap, jangan lupa nyalain konsol.”",
  "“Lo gak harus jago buat mulai, tapi lo harus mulai buat jadi jago.”",
  "“Banyakin ngoding, biar jari lo bisa auto type skill kayak Killua.” ⚡",
  "“Kegagalan itu bumbu, biar kesuksesan rasanya lebih enak.”",
  "“Jangan nunggu mood, mood itu dateng pas lo udah mulai.”",
  "“Mimpi itu ditulis pake keringat, bukan cuma kata-kata.”",
  "“Rencana tanpa aksi itu cuma halu.”",
  "“Lo ngerasa takut? Itu artinya lo lagi tumbuh.”",
  "“Gagal sekali bukan berarti lo gagal selamanya.”",
  "“Kuasai logika, maka dunia website ada di genggaman lo.”",
  "“Skill itu kayak otot, makin dilatih makin kuat.”",
  "“Kalau capek, istirahat. Bukan nyerah.”",
  "“Ilmu yang gak diamalin itu kayak pedang tumpul, gak kepake.”",
  "“Cita-cita boleh tinggi, tapi commit push jangan lupa.”",
  "“Semua jagoan pernah jadi newbie.”",
  "“Yang penting bukan siapa yang cepat, tapi siapa yang konsisten.”",
  "“Belajar itu gak ada kata terlambat, kecuali lo gak mulai-mulai.”",
  "“Koding adalah seni, dan lo adalah senimannya.”",
  "“Setiap error punya cerita, tinggal gimana lo menyelesaikannya.”",
  "“Sabar itu part dari skill developer.”",
  "“Keep calm and console.log everything.”",
  "“Jangan dibandingin, karena proses tiap orang beda.”",
  "“Lo belajar buat masa depan lo, bukan buat impress orang lain.”",
  "“Fokus sama progress, bukan perfection.”",
  "“Ngoding itu sabar + trial and error + doa.”",
  "“Semua website hebat dimulai dari <html> yang polos.”",
  "“Debugging itu kayak detektif, bedanya musuh lo... lo sendiri.”",
  "“Gagal itu guru terbaik, asalkan lo gak cuekin.”",
  "“Hidup itu tentang belajar, gagal, dan ulangi sampe berhasil.”",
  "“Gak ngerti sekarang? Santai, besok juga bisa ngerti.”",
  "“Koding hari ini, dunia cerah esok hari.”",
  "“Lo bukan gagal, lo cuma belum berhasil.”",
  "“Yang penting mulai, nanti juga ngerti.”",
  "“Koding itu kayak main game RPG, lo naik level tiap latihan.”",
  "“Jangan nyerah sebelum browser lo nyerah duluan.”",
  "“Belajar = luka + kopi + senyum saat berhasil.”",
  "“Susah itu biasa, jadi jago itu pilihan.”",
  "“Yang penting bukan banyaknya waktu, tapi niatnya.”",
  "“Belajar itu bukan nunggu semangat, tapi bikin semangat dateng.”",
  "“Cuma orang sabar yang bisa ngetik ulang karena lupa save.” 😅",
  "“Kesalahan itu guru, asal jangan pacar orang.”",
  "“Jangan takut mulai dari 0, semua web juga awalnya kosong.”",
  "“Tiap baris kode, lo makin deket ke mimpi lo.”",
  "“Web impian lo dimulai dari satu tag <div>.”",
  "“Ngoding emang berat... kalo laptop-nya lowbat.” 🔋",
  "“Bukan gak bisa, cuma belum terbiasa.”",
  "“Bug itu ujian... sukses itu kelulusan.”",
  "“Setiap klik itu langkah ke depan.”",
  "“Kalo semua gampang, gak seru dong.”",
  "“Belajar hari ini, panen skill besok.”",
  "“Gua diem bukan berarti gak ngerti, gua cuma gak tertarik.”",
  "“Kalo lo gak suka gua, itu masalah lo.”",
  "“Orang yang banyak omong biasanya paling kosong.”",
  "“Gak semua orang pantas dikasih perhatian.”",
  "“Tenang, gua bukan tipe yang suka drama.”",
  "“Jangan sok kenal, gua bukan karakter publik.”",
  "“Lo boleh nyinyir, tapi hidup gua tetep jalan.”",
  "“Gua dingin bukan sombong, gua cuma udah capek basa-basi.”",
  "“Gak perlu validasi dari orang yang bahkan gak tau perjuangan gua.”",
  "“Lo bisa nilai gua, tapi gua yang tentuin arah hidup gua.”",
  "“Jangan kalah sama rasa malas, karena sukses gak dateng ke orang yang rebahan doang.”",
  "“Kalo gak ada jalan, lo bikin jalan sendiri.”",
  "“Kerja keras itu nyakitin sekarang, tapi manis nanti.”",
  "“Jangan nunggu siap, mulai aja dulu.”",
  "“Hidup bukan tentang siapa yang hebat, tapi siapa yang terus berusaha.”",
  "“Kesuksesan itu dibangun dari pilihan-pilihan kecil yang lo ambil tiap hari.”",
  "“Lo gagal? Bagus. Itu berarti lo nyoba.”",
  "“Setiap hari lo latihan, lo satu langkah lebih deket ke mimpi lo.”",
  "“Jangan cuma jadi penonton hidup orang lain, bikin cerita lo sendiri.”",
  "“Lo punya potensi besar, tinggal lo mau gerak atau enggak.”",
  "“Jadilah orang yang berkualitas, tidak menindas untuk menjadi yg teratas.”",
  "“Motivasi tanpa aksi hanyalah imajinasi,Jadilah seperti mutiara proses nya susah tapi hasil nya bagus.”",
  "“Lampu boelh redup, tapi hati jangan redup.”",


];



function generateQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  document.getElementById("quote").innerText = quotes[randomIndex];
}